- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
#    groups:
#      - name: emea-vars
#        nodes:
#         - node
         
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76
#      - name: node3
#        label: ubuntu-node3
        
- nodeset:
    name: gate-node
    nodes:
      - name: gate
        label: centos76 

- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
#    group-vars:
#      emea-vars:
#        myname: "juhi"
#    vars:
#      emea_jfrog: "http://172.31.27.120:9081"
#      nafta_jfrog: "http://172.31.20.75:9082"

- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base
    
- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base
    
- job:
    name: helloworldjob
    run: playbooks/helloworld.yaml
    parent: base    


- project:
#    vars:
#      myname: "juhi"
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node
    check_emea:
      jobs:
        - demomavenbuildjob:
            host-vars:
              node:
                jfrog: "http://172.31.27.120:9081"
                jfrog_api_token: "AKCp5dK4z1yg9pvS3QoLtzwpMUbTrN5edVNpyv9pHnThHBze7PoFGTEHMeJhcaT6tRXR8bt7Q"
            nodeset: emea-node
    check_nafta:
      jobs:
        - demomavenbuildjob:
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9082"
                jfrog_api_token: "AKCp5dK4wtavETSJAiGFMbVRpe7YeGa8WdPzNmzqtvukpUnPdpschfY1RtrZXadQCpSHpAm4d"
            nodeset: nafta-node
    gate:
      jobs:
        - demomavenbuildjob:
            nodeset: nafta-node              
