- hosts: all
  tasks:
    - debug:
        msg: "running for gameof life demo"
#    - debug: 
#         msg: "{{ emea_jfrog }}"
#    - debug:
#        msg: "{{ nafta_jfrog }}"
        
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/gameoflife.git
        dest: ~/work/
      when: clean_output is succeeded
      
    - name: Build sample project
      shell: |
            /opt/maven/apache-maven-3.5.4/bin/mvn -f ~/work/pom.xml clean install
      register: output
      
    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ nafta_jfrog }}/artifactory/generic-local/gameoflife.war"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: AKCp5dK4un9rhNwegiiRP2GNEWijqzYYbxoawz6QzHVFuU5VWpGGXdzaTSV5eLEpoan64FpQW
        src: ~/work/gameoflife-web/target/gameoflife.war
        status_code: 201
        remote_src: yes
