- hosts: all
  tasks:
    - debug:
        msg: "game of life demo"
 
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/gameoflife.git
        dest: ~/work/
      when: clean_output is succeeded
      
    - name: Build sample project and junit reports 
      shell: |
            mvn -f ~/work/pom.xml clean install
            mvn -f ~/work/pom.xml surefire-report:report
      register: build_status
      
    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ jfrog }}/artifactory/generic-local/gameoflife.war"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: "{{ jfrog_api_token }}"
        src: ~/work/gameoflife-web/target/gameoflife.war
        status_code: 201
        remote_src: yes
      when: build_status is succeeded
      
    - name: Upload junit and jacoco reports to logs dir
      synchronize:
        mode: pull
        src: /home/ec2-user/work/gameoflife-web/target/site/
        dest: "{{ zuul.executor.log_root }}/"
      when: build_status is succeeded
